version: '3'
services:

    db:
        image: postgres
        container_name: postgres
        restart: always
        tty: true
        environment:
            POSTGRES_PASSWORD: "gustavo01"
            POSTGRES_DB: "minhadatabase"
        ports:
            - "15432:5432"

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "gustavo.torregrosa@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "gustavo01"
        ports:
            - "16543:80"
        depends_on:
            - db

  